version: '3.9'
services:
  bot:
    build: .
    container_name: language_bot
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    command: python bot.py

  db:
    image: postgres:15
    container_name: language_bot_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: